library;

import 'package:flutter/material.dart';

import 'constants.dart';

enum FilmProcess { c41, e6, blackAndWhite, instant, cinematic }

class FilmStock {
  final String id;
  final String name;
  final String shortName;
  final String description;
  final Color badgeColor;
  final IconData icon;
  final FilmProcess filmProcess;
  final int iso;
  final double temperature;
  final double saturation;
  final double contrast;
  final double brightness;
  final double shadowLift;
  final Color highlightTint;
  final Color shadowTint;
  final double tintStrength;
  final double baseGrain;
  final bool coloredGrain;
  final double grainSize;
  final double baseVignette;
  final double halation;
  final double redGamma;
  final double greenGamma;
  final double blueGamma;

  const FilmStock({
    required this.id,
    required this.name,
    required this.shortName,
    required this.description,
    required this.badgeColor,
    required this.icon,
    required this.filmProcess,
    required this.iso,
    required this.temperature,
    required this.saturation,
    required this.contrast,
    required this.brightness,
    required this.shadowLift,
    required this.highlightTint,
    required this.shadowTint,
    required this.tintStrength,
    required this.baseGrain,
    required this.coloredGrain,
    this.grainSize = 1.0,
    required this.baseVignette,
    this.halation = 0.0,
    required this.redGamma,
    required this.greenGamma,
    required this.blueGamma,
  });

  String get processLabel => switch (filmProcess) {
    FilmProcess.c41 => 'C-41',
    FilmProcess.e6 => 'E-6',
    FilmProcess.blackAndWhite => 'B&W',
    FilmProcess.instant => 'Instant',
    FilmProcess.cinematic => 'ECN-2',
  };
}

class FilmStocks {
  FilmStocks._();

  static const List<FilmStock> all = [
    kodakGold200,
    kodakUltramax400,
    kodakPortra400,
    kodakEktar100,
    fujiSuperia400,
    agfaVista200,
    fujiVelvia50,
    fujiProvia100F,
    ilfordHP5,
    kodakTriX400,
    ilfordDelta100,
    cineStill800T,
    cineStill50D,
    polaroid600,
    lomo400,
    expired1998,
    disposableFlash800,
    pocket110,
  ];

  static const FilmStock kodakGold200 = FilmStock(
    id: 'kodak_gold_200',
    name: 'K-Gold 200',
    shortName: 'GOLD',
    description: 'Warm, nostalgic daylight color.',
    badgeColor: Color(0xFFFFC107),
    icon: Icons.wb_sunny,
    filmProcess: FilmProcess.c41,
    iso: 200,
    temperature: 0.16,
    saturation: 1.20,
    contrast: 0.18,
    brightness: 0.01,
    shadowLift: 0.035,
    highlightTint: Color(0xFFF4D36A),
    shadowTint: Color(0xFF5A4030),
    tintStrength: 0.11,
    baseGrain: 0.12,
    coloredGrain: true,
    grainSize: 1.00,
    baseVignette: 0.24,
    redGamma: 0.96,
    greenGamma: 1.00,
    blueGamma: 1.05,
  );

  static const FilmStock kodakUltramax400 = FilmStock(
    id: 'kodak_ultramax_400',
    name: 'Kodak Ultramax 400',
    shortName: 'UMAX 400',
    description: 'Punchy consumer negative with a warm push.',
    badgeColor: Color(0xFFE65100),
    icon: Icons.filter_vintage,
    filmProcess: FilmProcess.c41,
    iso: 400,
    temperature: 0.10,
    saturation: 1.22,
    contrast: 0.23,
    brightness: 0.01,
    shadowLift: 0.030,
    highlightTint: Color(0xFFF3C07B),
    shadowTint: Color(0xFF4B3428),
    tintStrength: 0.09,
    baseGrain: 0.14,
    coloredGrain: true,
    grainSize: 1.10,
    baseVignette: 0.27,
    redGamma: 0.97,
    greenGamma: 0.99,
    blueGamma: 1.03,
  );

  static const FilmStock kodakPortra400 = FilmStock(
    id: 'portra_400',
    name: 'P-Portra 400',
    shortName: 'PRT400',
    description: 'Balanced skin tones and soft highlights.',
    badgeColor: Color(0xFFFF8A65),
    icon: Icons.face,
    filmProcess: FilmProcess.c41,
    iso: 400,
    temperature: 0.07,
    saturation: 0.95,
    contrast: -0.08,
    brightness: 0.02,
    shadowLift: 0.045,
    highlightTint: Color(0xFFF5C3B0),
    shadowTint: Color(0xFF4B5661),
    tintStrength: 0.08,
    baseGrain: 0.10,
    coloredGrain: true,
    grainSize: 0.95,
    baseVignette: 0.18,
    redGamma: 0.97,
    greenGamma: 1.00,
    blueGamma: 1.03,
  );

  static const FilmStock kodakEktar100 = FilmStock(
    id: 'kodak_ektar_100',
    name: 'Kodak Ektar 100',
    shortName: 'EKTAR',
    description: 'Fine grain, crisp reds, vivid landscapes.',
    badgeColor: Color(0xFFC62828),
    icon: Icons.landscape,
    filmProcess: FilmProcess.c41,
    iso: 100,
    temperature: 0.03,
    saturation: 1.30,
    contrast: 0.24,
    brightness: 0.00,
    shadowLift: 0.020,
    highlightTint: Color(0xFFFFB08B),
    shadowTint: Color(0xFF223567),
    tintStrength: 0.07,
    baseGrain: 0.06,
    coloredGrain: true,
    grainSize: 0.75,
    baseVignette: 0.18,
    redGamma: 0.96,
    greenGamma: 0.99,
    blueGamma: 1.02,
  );

  static const FilmStock fujiSuperia400 = FilmStock(
    id: 'fuji_superia_400',
    name: 'F-Superia 400',
    shortName: 'SUP400',
    description: 'Cooler greens and classic mini-lab color.',
    badgeColor: Color(0xFF4CAF50),
    icon: Icons.grass,
    filmProcess: FilmProcess.c41,
    iso: 400,
    temperature: -0.06,
    saturation: 1.20,
    contrast: 0.22,
    brightness: 0.00,
    shadowLift: 0.030,
    highlightTint: Color(0xFFCFE5B0),
    shadowTint: Color(0xFF274B3A),
    tintStrength: 0.10,
    baseGrain: 0.14,
    coloredGrain: true,
    grainSize: 1.10,
    baseVignette: 0.28,
    redGamma: 1.03,
    greenGamma: 0.97,
    blueGamma: 1.00,
  );

  static const FilmStock agfaVista200 = FilmStock(
    id: 'agfa_vista_200',
    name: 'A-Vista 200',
    shortName: 'VISTA',
    description: 'Saturated consumer color with lively reds.',
    badgeColor: Color(0xFFF44336),
    icon: Icons.local_fire_department,
    filmProcess: FilmProcess.c41,
    iso: 200,
    temperature: 0.05,
    saturation: 1.24,
    contrast: 0.22,
    brightness: 0.01,
    shadowLift: 0.035,
    highlightTint: Color(0xFFF2B574),
    shadowTint: Color(0xFF5B2F4A),
    tintStrength: 0.10,
    baseGrain: 0.12,
    coloredGrain: true,
    grainSize: 1.00,
    baseVignette: 0.24,
    redGamma: 0.97,
    greenGamma: 1.01,
    blueGamma: 0.99,
  );

  static const FilmStock fujiVelvia50 = FilmStock(
    id: 'fuji_velvia_50',
    name: 'Fuji Velvia 50',
    shortName: 'VELVIA',
    description: 'Punchy slide film with dense color.',
    badgeColor: Color(0xFF00838F),
    icon: Icons.filter_hdr,
    filmProcess: FilmProcess.e6,
    iso: 50,
    temperature: 0.00,
    saturation: 1.34,
    contrast: 0.32,
    brightness: -0.01,
    shadowLift: 0.005,
    highlightTint: Color(0xFFF4F0D0),
    shadowTint: Color(0xFF1E4474),
    tintStrength: 0.07,
    baseGrain: 0.05,
    coloredGrain: true,
    grainSize: 0.70,
    baseVignette: 0.16,
    redGamma: 0.99,
    greenGamma: 0.96,
    blueGamma: 0.98,
  );

  static const FilmStock fujiProvia100F = FilmStock(
    id: 'fuji_provia_100f',
    name: 'Fuji Provia 100F',
    shortName: 'PROVIA',
    description: 'Neutral slide film with clean contrast.',
    badgeColor: Color(0xFF1E88E5),
    icon: Icons.filter,
    filmProcess: FilmProcess.e6,
    iso: 100,
    temperature: -0.02,
    saturation: 1.12,
    contrast: 0.20,
    brightness: 0.00,
    shadowLift: 0.005,
    highlightTint: Color(0xFFF4F1DD),
    shadowTint: Color(0xFF263B5E),
    tintStrength: 0.05,
    baseGrain: 0.05,
    coloredGrain: true,
    grainSize: 0.70,
    baseVignette: 0.14,
    redGamma: 1.00,
    greenGamma: 0.98,
    blueGamma: 0.99,
  );

  static const FilmStock ilfordHP5 = FilmStock(
    id: 'ilford_hp5',
    name: 'I-HP5 Plus',
    shortName: 'HP5+',
    description: 'Classic black and white with open shadows.',
    badgeColor: Color(0xFF424242),
    icon: Icons.contrast,
    filmProcess: FilmProcess.blackAndWhite,
    iso: 400,
    temperature: 0.00,
    saturation: 0.00,
    contrast: 0.22,
    brightness: 0.00,
    shadowLift: 0.025,
    highlightTint: Colors.white,
    shadowTint: Colors.black,
    tintStrength: 0.00,
    baseGrain: 0.15,
    coloredGrain: false,
    grainSize: 1.15,
    baseVignette: 0.24,
    redGamma: 1.00,
    greenGamma: 1.00,
    blueGamma: 1.00,
  );

  static const FilmStock kodakTriX400 = FilmStock(
    id: 'kodak_tri_x_400',
    name: 'Kodak Tri-X 400',
    shortName: 'TRI-X',
    description: 'Punchier monochrome with classic street contrast.',
    badgeColor: Color(0xFF616161),
    icon: Icons.monochrome_photos,
    filmProcess: FilmProcess.blackAndWhite,
    iso: 400,
    temperature: 0.00,
    saturation: 0.00,
    contrast: 0.34,
    brightness: 0.00,
    shadowLift: 0.015,
    highlightTint: Colors.white,
    shadowTint: Colors.black,
    tintStrength: 0.00,
    baseGrain: 0.16,
    coloredGrain: false,
    grainSize: 1.20,
    baseVignette: 0.22,
    redGamma: 0.95,
    greenGamma: 1.00,
    blueGamma: 1.04,
  );

  static const FilmStock ilfordDelta100 = FilmStock(
    id: 'ilford_delta_100',
    name: 'Ilford Delta 100',
    shortName: 'DELTA',
    description: 'Clean black and white with fine grain.',
    badgeColor: Color(0xFFBDBDBD),
    icon: Icons.tonality,
    filmProcess: FilmProcess.blackAndWhite,
    iso: 100,
    temperature: 0.00,
    saturation: 0.00,
    contrast: 0.14,
    brightness: 0.01,
    shadowLift: 0.015,
    highlightTint: Colors.white,
    shadowTint: Colors.black,
    tintStrength: 0.00,
    baseGrain: 0.08,
    coloredGrain: false,
    grainSize: 0.65,
    baseVignette: 0.14,
    redGamma: 0.99,
    greenGamma: 1.00,
    blueGamma: 1.02,
  );

  static const FilmStock cineStill800T = FilmStock(
    id: 'cinestill_800t',
    name: 'C-Still 800T',
    shortName: '800T',
    description: 'Neon night look with tungsten halation.',
    badgeColor: Color(0xFF29B6F6),
    icon: Icons.nightlife,
    filmProcess: FilmProcess.cinematic,
    iso: 800,
    temperature: -0.14,
    saturation: 1.14,
    contrast: 0.23,
    brightness: 0.01,
    shadowLift: 0.030,
    highlightTint: Color(0xFFFFA08C),
    shadowTint: Color(0xFF1C4A72),
    tintStrength: 0.14,
    baseGrain: 0.18,
    coloredGrain: true,
    grainSize: 1.30,
    baseVignette: 0.28,
    halation: 0.32,
    redGamma: 0.98,
    greenGamma: 1.00,
    blueGamma: 0.94,
  );

  static const FilmStock cineStill50D = FilmStock(
    id: 'cinestill_50d',
    name: 'CineStill 50D',
    shortName: '50D',
    description: 'Daylight cinema color with light halation.',
    badgeColor: Color(0xFFFFA726),
    icon: Icons.movie_filter,
    filmProcess: FilmProcess.cinematic,
    iso: 50,
    temperature: 0.03,
    saturation: 1.10,
    contrast: 0.15,
    brightness: 0.00,
    shadowLift: 0.020,
    highlightTint: Color(0xFFFFB39E),
    shadowTint: Color(0xFF2F5960),
    tintStrength: 0.08,
    baseGrain: 0.07,
    coloredGrain: true,
    grainSize: 0.75,
    baseVignette: 0.16,
    halation: 0.12,
    redGamma: 0.98,
    greenGamma: 1.00,
    blueGamma: 1.02,
  );

  static const FilmStock polaroid600 = FilmStock(
    id: 'polaroid_600',
    name: 'Polaroid 600',
    shortName: 'POL 600',
    description: 'Soft instant color with lifted blacks.',
    badgeColor: RetroColors.polaroidWhite,
    icon: Icons.photo,
    filmProcess: FilmProcess.instant,
    iso: 160,
    temperature: 0.05,
    saturation: 0.84,
    contrast: -0.12,
    brightness: 0.02,
    shadowLift: 0.070,
    highlightTint: Color(0xFFF3E5F5),
    shadowTint: Color(0xFF344C8A),
    tintStrength: 0.13,
    baseGrain: 0.09,
    coloredGrain: true,
    grainSize: 0.95,
    baseVignette: 0.20,
    redGamma: 0.99,
    greenGamma: 1.00,
    blueGamma: 0.98,
  );

  static const FilmStock lomo400 = FilmStock(
    id: 'lomo_400',
    name: 'Lomo 400',
    shortName: 'LOMO',
    description: 'Cross-processed color and heavier vignette.',
    badgeColor: RetroColors.lomoBlue,
    icon: Icons.palette,
    filmProcess: FilmProcess.c41,
    iso: 400,
    temperature: 0.08,
    saturation: 1.32,
    contrast: 0.28,
    brightness: 0.01,
    shadowLift: 0.025,
    highlightTint: Color(0xFFFFE066),
    shadowTint: Color(0xFF184C8C),
    tintStrength: 0.15,
    baseGrain: 0.14,
    coloredGrain: true,
    grainSize: 1.15,
    baseVignette: 0.38,
    redGamma: 0.96,
    greenGamma: 1.03,
    blueGamma: 0.97,
  );

  static const FilmStock expired1998 = FilmStock(
    id: 'expired_1998',
    name: 'Expired 1998',
    shortName: 'EXP 98',
    description: 'Faded scans, magenta drift, old-box mood.',
    badgeColor: RetroColors.expiredPink,
    icon: Icons.auto_awesome,
    filmProcess: FilmProcess.c41,
    iso: 200,
    temperature: 0.09,
    saturation: 0.80,
    contrast: -0.08,
    brightness: 0.02,
    shadowLift: 0.080,
    highlightTint: Color(0xFFE6B68A),
    shadowTint: Color(0xFF66445C),
    tintStrength: 0.18,
    baseGrain: 0.16,
    coloredGrain: true,
    grainSize: 1.25,
    baseVignette: 0.30,
    redGamma: 0.95,
    greenGamma: 1.04,
    blueGamma: 1.00,
  );

  static const FilmStock disposableFlash800 = FilmStock(
    id: 'disposable_flash_800',
    name: 'Disposable Flash 800',
    shortName: 'FLASH',
    description: 'Direct flash look, cool shadows, loud memories.',
    badgeColor: Color(0xFFFF7043),
    icon: Icons.flash_on,
    filmProcess: FilmProcess.c41,
    iso: 800,
    temperature: -0.02,
    saturation: 1.20,
    contrast: 0.28,
    brightness: 0.03,
    shadowLift: 0.020,
    highlightTint: Color(0xFFFFF1CE),
    shadowTint: Color(0xFF33485D),
    tintStrength: 0.09,
    baseGrain: 0.18,
    coloredGrain: true,
    grainSize: 1.35,
    baseVignette: 0.34,
    redGamma: 1.02,
    greenGamma: 0.99,
    blueGamma: 0.97,
  );

  static const FilmStock pocket110 = FilmStock(
    id: 'pocket_110',
    name: 'Pocket 110',
    shortName: '110',
    description: 'Tiny-camera color, faded mids, coarse grain.',
    badgeColor: Color(0xFF8D6E63),
    icon: Icons.camera_alt_outlined,
    filmProcess: FilmProcess.c41,
    iso: 200,
    temperature: 0.09,
    saturation: 0.90,
    contrast: -0.06,
    brightness: 0.01,
    shadowLift: 0.065,
    highlightTint: Color(0xFFE8B97A),
    shadowTint: Color(0xFF66445C),
    tintStrength: 0.15,
    baseGrain: 0.20,
    coloredGrain: true,
    grainSize: 1.55,
    baseVignette: 0.42,
    redGamma: 0.96,
    greenGamma: 1.03,
    blueGamma: 0.99,
  );

  static FilmStock getById(String id) {
    return all.firstWhere(
      (stock) => stock.id == id,
      orElse: () => kodakGold200,
    );
  }

  static Map<FilmProcess, List<FilmStock>> get byProcess {
    final groups = <FilmProcess, List<FilmStock>>{};
    for (final stock in all) {
      groups.putIfAbsent(stock.filmProcess, () => []).add(stock);
    }
    return groups;
  }
}
